apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: api
    app.kubernetes.io/name: backend-http
    app.kubernetes.io/part-of: demo
spec:
  containers:
    - name: httpbin
      image: mccutchen/go-httpbin:2.22.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
