apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: backend-a-mtls-route
  namespace: backend-a
  labels:
    app.kubernetes.io/part-of: demo
spec:
  parentRefs:
    - name: mtls-multi-namespace-gateway
      namespace: gateway-system
      sectionName: mtls
  hostnames:
    - mtls-a.example.test
  rules:
    - backendRefs:
        - name: backend-mtls
          port: 9443
