# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-gateway-system-namespace.yaml
  - 00-backend-a-namespace.yaml
  - 00-backend-b-namespace.yaml
  - 12-backend-a-pki.yaml
  - 12-backend-b-pki.yaml
  - instances/backend-http-a
  - instances/backend-http-b
  - instances/backend-grpc-a
  - instances/backend-grpc-b
  - instances/backend-mtls-a
  - instances/backend-mtls-b
