# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumenvoyextprocfilter_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumEnvoyExtProcFilter
metadata:
  name: order-a
  namespace: ext-proc-ordering
spec:
  backendRef:
    name: ext-proc-backend
    port: 4317
  processingMode:
    requestHeaderMode: SEND
    responseHeaderMode: SKIP
    requestBodyMode: NONE
    responseBodyMode: NONE
---
apiVersion: cilium.io/v2alpha1
kind: CiliumEnvoyExtProcFilter
metadata:
  name: order-b
  namespace: ext-proc-ordering
spec:
  backendRef:
    name: ext-proc-backend
    port: 4317
  processingMode:
    requestHeaderMode: SEND
    responseHeaderMode: SKIP
    requestBodyMode: NONE
    responseBodyMode: NONE
---
apiVersion: cilium.io/v2alpha1
kind: CiliumEnvoyExtProcFilter
metadata:
  name: order-c
  namespace: ext-proc-ordering
spec:
  backendRef:
    name: ext-proc-backend
    port: 4317
  processingMode:
    requestHeaderMode: SEND
    responseHeaderMode: SKIP
    requestBodyMode: NONE
    responseBodyMode: NONE
---
apiVersion: cilium.io/v2alpha1
kind: CiliumEnvoyExtProcFilter
metadata:
  name: losing-only-d
  namespace: ext-proc-ordering
spec:
  backendRef:
    name: ext-proc-backend
    port: 4317
  processingMode:
    requestHeaderMode: SEND
    responseHeaderMode: SKIP
    requestBodyMode: NONE
    responseBodyMode: NONE
