# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/backend-mtls
namespace: backend-b
patches:
  - target:
      kind: Pod
      name: backend-mtls
    patch: |-
      - op: replace
        path: /spec/volumes/1/secret/secretName
        value: backend-b-mtls-server
