[tasks.start]
extends = "scenario:start"
description = "Deploy the TLS gRPC Gateway API scenario"
depends = ["//:kind:load:apps{% if usage.verbose %} --verbose{% endif %}", "//:cert-manager:install"]

[tasks.verify]
extends = "scenario:verify"
description = "Verify the TLS gRPC Gateway API scenario"

[tasks.delete]
extends = "scenario:delete"
