[tasks.start]
extends = "scenario:start"
description = "Deploy the HTTP→HTTPS redirect scenario"
depends = ["//:kind:load:apps{% if usage.verbose %} --verbose{% endif %}"]

[tasks.verify]
extends = "scenario:verify"
description = "Verify the HTTP→HTTPS redirect scenario"

[tasks.delete]
extends = "scenario:delete"
