apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-ext-proc-filters-to-coraza-waf
  namespace: gateway-system
spec:
  from:
    - group: cilium.io
      kind: CiliumEnvoyExtProcFilter
      namespace: backend-a
    - group: cilium.io
      kind: CiliumEnvoyExtProcFilter
      namespace: backend-b
  to:
    - group: ""
      kind: Service
      name: coraza-waf-extproc
