# Cilium 1.19.3 — latest stable (default in mise.toml)
[env]
CILIUM_VERSION = "1.19.3"
GATEWAY_API_VERSION = "1.4.1"
X_GRPCROUTE_ACCEPTED_MSG = "Accepted HTTPRoute"
X_TLSROUTE_ACCEPTED_MSG = "Accepted HTTPRoute"
X_TLSROUTE_API_VERSION = "v1alpha2"
X_ALLOWED_ROUTES_SEPARATE_PORT_BROKEN = "true"
X_ALLOWED_ROUTES_SHARED_PORT_BROKEN = "false"
X_SPLIT_PORT_GRPC_BROKEN = "true"
X_TLSROUTE_NO_SECTIONNAME_BROKEN = "true"
X_TLS_PASSTHROUGH_SPLIT_PORTS_BROKEN = "true"
X_ALLOWED_ROUTES_NAMESPACES_BROKEN = "true"
X_HTTPS_TLS_SPLIT_PORT_BROKEN = "true"
