# Cilium 1.20.0-pre.1 — latest pre-release
[env]
CILIUM_VERSION = "1.20.0-pre.1"
GATEWAY_API_VERSION = "1.5.1"
X_GRPCROUTE_ACCEPTED_MSG = "Accepted GRPCRoute"
X_TLSROUTE_ACCEPTED_MSG = "Accepted TLSRoute"
X_TLSROUTE_API_VERSION = "v1"
X_ALLOWED_ROUTES_SEPARATE_PORT_BROKEN = "true"
X_ALLOWED_ROUTES_SHARED_PORT_BROKEN = "false"
X_SPLIT_PORT_GRPC_BROKEN = "true"
