apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: https-grpc-gateway-certificate
  namespace: gateway-system
spec:
  secretName: https-grpc-gateway-tls
  commonName: https-a.example.test
  dnsNames:
    - "*.example.test"
    - https-a.example.test
    - https-b.example.test
    - grpc-a.example.test
    - grpc-b.example.test
    - localhost
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    kind: Issuer
    name: https-grpc-selfsigned
