# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../00-services.yaml
  - ../10-ext-proc-filters.yaml
  - ../20-foundation-route.yaml
  - ../21-multi-parent-routes.yaml
