apiVersion: v1
kind: Service
metadata:
  name: grpc-api
  labels:
    app: grpc-api
    app.kubernetes.io/name: backend-grpc
    app.kubernetes.io/part-of: demo
spec:
  selector:
    app: grpc-api
  ports:
    - name: grpc
      port: 9000
      targetPort: grpc
      appProtocol: kubernetes.io/h2c
  type: ClusterIP
