# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-gateway-system-namespace.yaml
  - 00-backend-a-namespace.yaml
  - 00-backend-b-namespace.yaml
  - 10-allowed-routes-selfsigned-issuer.yaml
  - 11-allowed-routes-gateway-certificate.yaml
  - instances/backend-http-a
  - instances/backend-http-b
  - instances/backend-grpc-a
  - instances/backend-grpc-b
  - 30-gateway.yaml
  - 31-backend-a-https-route.yaml
  - 32-backend-b-https-route.yaml
  - 33-backend-a-grpcroute.yaml
  - 34-backend-b-grpcroute.yaml
