# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../10-ns-shared-port-selfsigned-issuer.yaml
  - ../11-ns-shared-port-gateway-certificate.yaml
  - ../30-gateway.yaml
  - ../31-cross-ns-httproute.yaml
