# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../30-gateway.yaml
  - ../31-backend-a-tlsroute.yaml
  - ../32-backend-b-tlsroute.yaml
