apiVersion: v1
kind: Pod
metadata:
  name: netshoot-client
  labels:
    app: netshoot-client
    app.kubernetes.io/name: netshoot-client
    app.kubernetes.io/part-of: demo
spec:
  containers:
    - name: netshoot
      image: nicolaka/netshoot:v0.15
      imagePullPolicy: IfNotPresent
      command: ["sleep", "infinity"]
