# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../config/namespaces/gateway-system.yaml
  - 00-backend-a-namespace.yaml
  - 00-auth-namespace.yaml
  - ../../../config/instances/backend-http-a
  - 20-auth-referencegrant.yaml
  - 30-gateway.yaml
  - 32-httproute.yaml
