apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-b-https-route
  namespace: backend-b
  labels:
    app.kubernetes.io/part-of: demo
spec:
  parentRefs:
    - name: shared-port-gateway
      namespace: gateway-system
      sectionName: https
  hostnames:
    - backend-b.example.test
  rules:
    - backendRefs:
        - name: api
          port: 80
