apiVersion: v1
kind: Pod
metadata:
  name: backend-mtls
  labels:
    app: backend-mtls
    app.kubernetes.io/name: backend-mtls
    app.kubernetes.io/part-of: demo
spec:
  containers:
    - name: envoy
      image: envoyproxy/envoy:v1.33.2
      imagePullPolicy: IfNotPresent
      args:
        - -c
        - /etc/envoy/envoy.yaml
        - --service-cluster
        - backend-mtls
        - --log-level
        - info
      ports:
        - name: tls
          containerPort: 9443
      volumeMounts:
        - name: backend-mtls-config
          mountPath: /etc/envoy/envoy.yaml
          subPath: envoy.yaml
        - name: backend-mtls-cert
          mountPath: /etc/envoy/tls
          readOnly: true
  volumes:
    - name: backend-mtls-config
      configMap:
        name: backend-mtls-config
    - name: backend-mtls-cert
      secret:
        secretName: replace-me
