apiVersion: v1
kind: Service
metadata:
  name: backend-mtls
  labels:
    app: backend-mtls
    app.kubernetes.io/name: backend-mtls
    app.kubernetes.io/part-of: demo
spec:
  selector:
    app: backend-mtls
  ports:
    - name: tls
      port: 9443
      targetPort: tls
  type: ClusterIP
