apiVersion: v1
kind: Service
metadata:
  name: coraza-waf-extproc
  labels:
    app: coraza-waf-extproc
    app.kubernetes.io/name: coraza-waf-extproc
    app.kubernetes.io/part-of: demo
spec:
  selector:
    app: coraza-waf-extproc
  ports:
    - name: grpc
      port: 4317
      targetPort: grpc
      appProtocol: kubernetes.io/h2c
  type: ClusterIP
