apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: backend-b-grpc-route
  namespace: backend-b
  labels:
    app.kubernetes.io/part-of: demo
spec:
  parentRefs:
    - name: allowed-routes-gateway
      namespace: gateway-system
      sectionName: grpcs
  hostnames:
    - grpc-b.example.test
  rules:
    - backendRefs:
        - name: grpc-api
          port: 9000
