---
apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  annotations:
    cec.cilium.io/use-original-source-address: "false"
  creationTimestamp: "2026-04-23T05:22:30Z"
  generation: 1
  labels:
    gateway.networking.k8s.io/gateway-name: allowed-routes-gateway
  name: cilium-gateway-allowed-routes-gateway
  namespace: gateway-system
  ownerReferences:
    - apiVersion: gateway.networking.k8s.io/v1
      controller: true
      kind: Gateway
      name: allowed-routes-gateway
      uid: 11fd4e11-44e5-4e4f-95bf-0eb73eeb3194
  resourceVersion: "5141"
  uid: 14bfcb40-e2eb-4c1f-ab57-4695594971b8
spec:
  backendServices:
    - name: grpc-api
      namespace: backend-a
      number:
        - "9000"
    - name: grpc-api
      namespace: backend-b
      number:
        - "9000"
  resources:
    - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
      additionalAddresses:
        - address:
            socketAddress:
              address: 0.0.0.0
              portValue: 50051
      address:
        socketAddress:
          address: 0.0.0.0
          portValue: 443
      filterChains:
        - filterChainMatch:
            transportProtocol: raw_buffer
          filters:
            - name: envoy.filters.network.http_connection_manager
              typedConfig:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                commonHttpProtocolOptions:
                  maxStreamDuration: 0s
                httpFilters:
                  - name: envoy.filters.http.grpc_web
                    typedConfig:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                  - name: envoy.filters.http.grpc_stats
                    typedConfig:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
                      emitFilterState: true
                      enableUpstreamStats: true
                  - name: envoy.filters.http.router
                    typedConfig:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                internalAddressConfig:
                  cidrRanges:
                    - addressPrefix: 10.0.0.0
                      prefixLen: 8
                    - addressPrefix: 172.16.0.0
                      prefixLen: 12
                    - addressPrefix: 192.168.0.0
                      prefixLen: 16
                    - addressPrefix: 127.0.0.1
                      prefixLen: 32
                rds:
                  routeConfigName: listener-insecure
                statPrefix: listener-insecure
                streamIdleTimeout: 300s
                upgradeConfigs:
                  - upgradeType: websocket
                useRemoteAddress: true
        - filterChainMatch:
            serverNames:
              - "*.example.test"
              - "*.example.test"
            transportProtocol: tls
          filters:
            - name: envoy.filters.network.http_connection_manager
              typedConfig:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                commonHttpProtocolOptions:
                  maxStreamDuration: 0s
                httpFilters:
                  - name: envoy.filters.http.grpc_web
                    typedConfig:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                  - name: envoy.filters.http.grpc_stats
                    typedConfig:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
                      emitFilterState: true
                      enableUpstreamStats: true
                  - name: envoy.filters.http.router
                    typedConfig:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                internalAddressConfig:
                  cidrRanges:
                    - addressPrefix: 10.0.0.0
                      prefixLen: 8
                    - addressPrefix: 172.16.0.0
                      prefixLen: 12
                    - addressPrefix: 192.168.0.0
                      prefixLen: 16
                    - addressPrefix: 127.0.0.1
                      prefixLen: 32
                rds:
                  routeConfigName: listener-secure
                statPrefix: listener-secure
                streamIdleTimeout: 300s
                upgradeConfigs:
                  - upgradeType: websocket
                useRemoteAddress: true
          transportSocket:
            name: envoy.transport_sockets.tls
            typedConfig:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              commonTlsContext:
                alpnProtocols:
                  - h2,http/1.1
                tlsCertificateSdsSecretConfigs:
                  - name: cilium-secrets/gateway-system-allowed-routes-gateway-tls
      listenerFilters:
        - name: envoy.filters.listener.tls_inspector
          typedConfig:
            "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
      name: listener
      socketOptions:
        - description: Enable TCP keep-alive (default to enabled)
          intValue: "1"
          level: "1"
          name: "9"
        - description: TCP keep-alive idle time (in seconds) (defaults to 10s)
          intValue: "10"
          level: "6"
          name: "4"
        - description: TCP keep-alive probe intervals (in seconds) (defaults to 5s)
          intValue: "5"
          level: "6"
          name: "5"
        - description: TCP keep-alive probe max failures.
          intValue: "10"
          level: "6"
          name: "6"
    - "@type": type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      name: listener-insecure
    - "@type": type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      name: listener-secure
      virtualHosts:
        - domains:
            - grpc-a.example.test
            - grpc-a.example.test:*
          name: grpc-a.example.test
          routes:
            - match:
                prefix: /
              route:
                cluster: backend-a:grpc-api:9000
                maxStreamDuration:
                  maxStreamDuration: 0s
        - domains:
            - grpc-b.example.test
            - grpc-b.example.test:*
          name: grpc-b.example.test
          routes:
            - match:
                prefix: /
              route:
                cluster: backend-b:grpc-api:9000
                maxStreamDuration:
                  maxStreamDuration: 0s
    - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      edsClusterConfig:
        serviceName: backend-a/grpc-api:9000
      name: backend-a:grpc-api:9000
      outlierDetection:
        splitExternalLocalOriginErrors: true
      type: EDS
      typedExtensionProtocolOptions:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          commonHttpProtocolOptions:
            idleTimeout: 60s
          explicitHttpConfig:
            http2ProtocolOptions: {}
    - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      edsClusterConfig:
        serviceName: backend-b/grpc-api:9000
      name: backend-b:grpc-api:9000
      outlierDetection:
        splitExternalLocalOriginErrors: true
      type: EDS
      typedExtensionProtocolOptions:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          commonHttpProtocolOptions:
            idleTimeout: 60s
          explicitHttpConfig:
            http2ProtocolOptions: {}
  services:
    - name: cilium-gateway-allowed-routes-gateway
      namespace: gateway-system
      ports:
        - 443
        - 50051
